executable            = CONDORDIR/submit.sh
arguments             = $(JOBNUM) BASEDIR X509PATH
output                = LOGDIR/JOBNAME.$(ClusterId).$(ProcId).out
error                 = LOGDIR/JOBNAME.$(ClusterId).$(ProcId).err
log                   = LOGDIR/JOBNAME.$(ClusterId).$(ProcId).log

should_transfer_files = YES
transfer_input_files  = INPUTFILES

request_memory 	      = 6000
+JobFlavour           = "tomorrow"
+SingularityImage     = IMAGE

Queue JOBNUM from JOBNUM_FILE
